import os
import json
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

try:
    from backend.services.question_selection.gdt_module import (
        parse_text_with_formula_pdf,
        render_gdt_to_pdf,
    )
    _GDT_AVAILABLE = True
except Exception:
    _GDT_AVAILABLE = False

def format_paper_to_pdf(paper_json, output_path):
    """
    Converts a Paper JSON (sections with questions) into a formatted PDF.
    """
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )

    # Styles
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        "Title",
        fontSize=18,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
        spaceAfter=12
    )
    
    metadata_style = ParagraphStyle(
        "Metadata",
        fontSize=10,
        fontName="Helvetica",
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    section_title_style = ParagraphStyle(
        "SectionTitle",
        fontSize=14,
        fontName="Helvetica-Bold",
        spaceBefore=18,
        spaceAfter=6,
        underlineWidth=1
    )
    
    instruction_style = ParagraphStyle(
        "Instruction",
        fontSize=10,
        fontName="Helvetica-Oblique",
        spaceAfter=10,
        leftIndent=0.5*cm
    )
    
    question_style = ParagraphStyle(
        "Question",
        fontSize=11,
        fontName="Helvetica",
        leading=14,
        spaceAfter=8,
        leftIndent=1*cm
    )

    story = []

    # 1. Header
    title = paper_json.get("title") or "Question Paper"
    story.append(Paragraph(title.upper(), title_style))
    
    subject = paper_json.get("subject") or "N/A"
    grade = paper_json.get("grade") or "N/A"
    marks = paper_json.get("total_marks") or "80"
    duration = paper_json.get("duration") or "3 Hours"
    
    meta_text = f"Subject: {subject}   |   Class: {grade}<br/>" \
                f"Total Marks: {marks}   |   Duration: {duration}"
    story.append(Paragraph(meta_text, metadata_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.black, spaceAfter=20))

    # 2. Sections
    sections = paper_json.get("sections", [])
    for idx, section in enumerate(sections):
        s_name = section.get("section_name") or f"Section {idx+1}"
        s_instr = section.get("section_description") or ""
        
        story.append(Paragraph(s_name.upper(), section_title_style))
        if s_instr:
            story.append(Paragraph(f"Instructions: {s_instr}", instruction_style))
        
        # Questions in section
        questions = section.get("questions", [])
        for q_idx, q in enumerate(questions):
            q_text = q.get("question_text") or q.get("text") or ""
            q_marks = q.get("marks") or ""
            q_id = q.get("id") or q.get("question_number") or str(q_idx)
            gdt_blocks = q.get("gdt") or []

            # Question label line
            label = f"<b>Q{q_idx+1}.</b>"
            if q_marks:
                label += f" <font color='grey'>[{q_marks}M]</font>"
            story.append(Paragraph(label, question_style))

            # Question text — split on $...$ formulas if GDT module available
            if _GDT_AVAILABLE and "$" in q_text:
                parse_text_with_formula_pdf(q_text, story)
            else:
                story.append(Paragraph(q_text, question_style))

            # GDT blocks (table / plot / graph_ds / formula)
            if gdt_blocks and _GDT_AVAILABLE:
                render_gdt_to_pdf(gdt_blocks, story, f"q{q_id}")

            story.append(Spacer(1, 6))

    # 3. Footer
    story.append(Spacer(1, 40))
    story.append(HRFlowable(width="50%", thickness=0.5, color=colors.grey, hAlign="CENTER", spaceAfter=10))
    footer_style = ParagraphStyle("Footer", fontSize=8, fontName="Helvetica-Oblique", alignment=TA_CENTER, textColor=colors.grey)
    story.append(Paragraph("End of Question Paper · Generated by QPilot", footer_style))

    doc.build(story)
    return output_path
