# -*- coding: utf-8 -*-
"""GDT module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjqAjBA8sdO9lbB0HjCPSlipNiUqcw9Y
"""

!pip install matplotlib pandas pillow networkx python-docx reportlab

import os
import re
import matplotlib.pyplot as plt
import pandas as pd
import networkx as nx

OUTPUT_DIR = "gdt_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

def save_clean_image(path):
    plt.savefig(path, bbox_inches='tight', pad_inches=0.05, dpi=150)
    plt.close()

def generate_plot(content, filename):
    plt.figure(figsize=(3.5,2.5))

    plt.plot(
        content["x"],
        content["y"],
        marker='o',
        color='black'
    )

    plt.xlabel(content.get("xlabel", ""), fontsize=8)
    plt.ylabel(content.get("ylabel", ""), fontsize=8)
    plt.title(content.get("title", ""), fontsize=9)

    plt.grid(True, linestyle='--', linewidth=0.5)

    path = os.path.join(OUTPUT_DIR, filename)
    save_clean_image(path)

    return path

def generate_graph_ds(content, filename):
    import networkx as nx
    import matplotlib.pyplot as plt
    import os

    G = nx.DiGraph() if content.get("directed", False) else nx.Graph()

    G.add_edges_from(content["edges"])

    plt.figure(figsize=(3,2.5))
    pos = nx.spring_layout(G, seed=42)

    nx.draw(
        G, pos,
        with_labels=True,
        node_size=800,
        node_color="white",
        edge_color="black",
        font_size=8,
        edgecolors="black"
    )

    # 🔥 FIX: Convert string keys to tuple
    if "edge_labels" in content:
        edge_labels = {
            eval(k): v for k, v in content["edge_labels"].items()
        }

        nx.draw_networkx_edge_labels(
            G, pos,
            edge_labels=edge_labels,
            font_size=7
        )

    path = os.path.join(OUTPUT_DIR, filename)
    plt.savefig(path, bbox_inches='tight', pad_inches=0.05, dpi=150)
    plt.close()

    return path

def generate_formula(content, filename):
    import matplotlib.pyplot as plt
    import os

    fig, ax = plt.subplots(figsize=(2, 0.6))  # VERY SMALL HEIGHT

    ax.text(
        0.5, 0.5,
        f"${content}$",
        fontsize=12,
        ha='center',
        va='center'
    )

    ax.axis('off')

    path = os.path.join(OUTPUT_DIR, filename)

    plt.savefig(
        path,
        bbox_inches='tight',
        pad_inches=0.0,   # 🔥 ZERO PADDING
        dpi=200           # sharper text
    )

    plt.close()
    return path

from docx import Document
from docx.shared import Inches
from docx.oxml import OxmlElement
from docx.oxml.ns import qn


# TABLE WITH BORDERS
def add_table_with_border(doc, content):
    table = doc.add_table(rows=1, cols=len(content["headers"]))

    for i, h in enumerate(content["headers"]):
        table.rows[0].cells[i].text = h

    for row in content["rows"]:
        cells = table.add_row().cells
        for i, val in enumerate(row):
            cells[i].text = str(val)

    # Add borders
    for row in table.rows:
        for cell in row.cells:
            tc = cell._tc
            tcPr = tc.get_or_add_tcPr()
            borders = OxmlElement('w:tcBorders')

            for edge in ('top', 'left', 'bottom', 'right'):
                elem = OxmlElement(f'w:{edge}')
                elem.set(qn('w:val'), 'single')
                elem.set(qn('w:sz'), '4')
                elem.set(qn('w:color'), '000000')
                borders.append(elem)

            tcPr.append(borders)


def add_text_with_formula_block(doc, text):
    import re
    from docx.shared import Inches

    parts = re.split(r'(\$.*?\$)', text)

    for part in parts:
        if part.startswith("$") and part.endswith("$"):
            formula = part.strip("$")
            img = generate_formula(formula, "temp_formula.png")

            doc.add_picture(img, width=Inches(2))

        else:
            if part.strip():
                p = doc.add_paragraph(part)
                p.paragraph_format.space_after = 0
                p.paragraph_format.space_before = 0

from docx import Document
from docx.shared import Inches


def generate_docx(questions, filename="paper.docx"):
    doc = Document()

    for q in questions:

        # 🔹 Handle text + formula (BLOCK STYLE)
        add_text_with_formula_block(doc, q["question_text"])

        # 🔹 Handle GDT elements
        for g in q.get("gdt", []):

            if g["type"] == "table":
                add_table_with_border(doc, g["content"])

            elif g["type"] == "plot":
                img = generate_plot(g["content"], f"{q['question_id']}_plot.png")
                doc.add_picture(img, width=Inches(3.5))

            elif g["type"] == "graph_ds":
                img = generate_graph_ds(g["content"], f"{q['question_id']}_graph.png")
                doc.add_picture(img, width=Inches(3.5))

        # 🔹 Minimal spacing between questions
        p = doc.add_paragraph()
        p.paragraph_format.space_after = 4
        p.paragraph_format.space_before = 0

    doc.save(filename)
    print("DOCX saved:", filename)

from reportlab.platypus import SimpleDocTemplate, Paragraph, Image, Spacer, Table, TableStyle
from reportlab.lib import styles, colors
from reportlab.lib.units import inch


def parse_text_with_formula_pdf(text, elements):
    import re
    from reportlab.platypus import Paragraph, Image
    from reportlab.lib.units import inch

    style = styles.getSampleStyleSheet()["Normal"]
    parts = re.split(r'(\$.*?\$)', text)

    for part in parts:
        if part.startswith("$") and part.endswith("$"):
            formula = part.strip("$")
            img = generate_formula(formula, "temp_formula.png")

            elements.append(Image(img, width=2*inch, height=0.4*inch))
        else:
            if part.strip():
                elements.append(Paragraph(part, style))


# TABLE WITH BORDERS (PDF)
def create_pdf_table(content):
    data = [content["headers"]] + content["rows"]

    table = Table(data)
    table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('ALIGN', (0,0), (-1,-1), 'CENTER')
    ]))

    return table


# PDF GENERATOR
def generate_pdf(questions, filename="paper.pdf"):
    doc = SimpleDocTemplate(filename)
    elements = []

    for q in questions:
        parse_text_with_formula_pdf(q["question_text"], elements)
        elements.append(Spacer(1, 8))

        for g in q.get("gdt", []):

            if g["type"] == "table":
                elements.append(create_pdf_table(g["content"]))

            elif g["type"] == "plot":
                img = generate_plot(g["content"], f"{q['question_id']}_plot.png")
                elements.append(Image(img, width=3.5*inch, height=2.5*inch))

            elif g["type"] == "graph_ds":
                img = generate_graph_ds(g["content"], f"{q['question_id']}_graph.png")
                elements.append(Image(img, width=3.5*inch, height=2.5*inch))

        elements.append(Spacer(1, 4))

    doc.build(elements)
    print("PDF saved:", filename)



questions = [
  {
    "question_id": "Q1",
    "question_text": "Given the following sequences, apply the Longest Increasing Subsequence algorithm to determine the length of the longest increasing subsequence for each sequence.",
    "marks": 5,
    "bloom": "Apply",
    "gdt": [
      {
        "type": "table",
        "content": {
          "headers": [
            "Sequence",
            "LIS Length"
          ],
          "rows": [
            ["3, 10, 2, 1, 20", ""],
            ["3, 2", ""],
            ["50, 3, 10, 7, 40, 80", ""],
            ["3, 4, 5, 1, 2, 6", ""]
          ]
        }
      }
    ]
  },
  {
    "question_id": "Q2",
    "question_text": "Analyze and compare a Binary Search Tree (BST) and a Balanced Binary Search Tree (BBST) in terms of search complexity and height.",
    "marks": 5,
    "bloom": "Analyze",
    "gdt": [
      {
        "type": "table",
        "content": {
          "headers": [
            "Tree Type",
            "Avg Search",
            "Worst Search",
            "Height"
          ],
          "rows": [
            ["BST", "O(log n)", "O(n)", "n"],
            ["BBST", "O(log n)", "O(log n)", "log n"]
          ]
        }
      }
    ]
  },
  {
    "question_id": "Q3",
    "question_text": "What is normalization in DBMS?",
    "marks": 2,
    "bloom": "Remember",
    "gdt": []
  },
  {
    "question_id": "Q4",
    "question_text": "Using Dijkstra's Algorithm, find the shortest path from vertex A to D.",
    "marks": 5,
    "bloom": "Apply",
    "gdt": [
      {
        "type": "graph_ds",
        "content": {
          "directed": True,
          "edges": [
            ["A", "B"],
            ["A", "C"],
            ["B", "C"],
            ["B", "D"],
            ["C", "D"]
          ],
          "edge_labels": {
            "(\"A\",\"B\")": 1,
            "(\"A\",\"C\")": 4,
            "(\"B\",\"C\")": 2,
            "(\"B\",\"D\")": 5,
            "(\"C\",\"D\")": 1
          }
        }
      }
    ]
  },
  {
    "question_id": "Q5",
    "question_text": "Explain the basic structure of a neural network and the role of each component.",
    "marks": 3,
    "bloom": "Understand",
    "gdt": []
  }
]

generate_docx(questions)
generate_pdf(questions)

from google.colab import files

files.download("paper.docx")
files.download("paper.pdf")

"""# Question generator code here"""

!pip install openai

import os
from openai import OpenAI
from google.colab import userdata

client = OpenAI(api_key=userdata.get("OPENAI_API_KEY"))

MODEL = "gpt-4o-mini"

response = client.models.generate_content(
    model="gemini-2.0-flash",
    contents="Say hello"
)

print(response.text)

def build_prompt(topic, bloom, marks):
    return f"""
You are an expert question paper generator.

INPUT:
- Topic: {topic}
- Bloom Level: {bloom}
- Marks: {marks}

RULES:

1. If marks <= 2:
   - simple question
   - no GDT

2. If marks >= 5 AND bloom in [Apply, Analyze]:
   - MUST include GDT if meaningful

3. GDT TYPES:
- table → comparisons
- plot → numeric / complexity
- graph_ds → trees, graphs

4. Output STRICT JSON:

{{
  "question_id": "QX",
  "question_text": "...",
  "marks": {marks},
  "bloom": "{bloom}",
  "gdt": [
    {{
      "type": "table | plot | graph_ds",
      "content": {{...}}
    }}
  ]
}}

5. Content rules:

table:
- headers
- rows

plot:
- x: list
- y: list

graph_ds:
- directed: true/false
- edges: list

NO explanation. ONLY JSON.

Generate now.
"""

import json

def generate_question(topic, bloom, marks):
    prompt = build_prompt(topic, bloom, marks)

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": "You generate structured exam questions."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3
    )

    text = response.choices[0].message.content.strip()

    # Clean formatting
    text = text.replace("```json", "").replace("```", "").strip()

    try:
        return json.loads(text)
    except:
        print("⚠️ JSON parsing failed:\n", text)
        return None

test_inputs = [
    ("Longest Increasing Subsequence", "Apply", 5),
    ("Binary Search Tree", "Analyze", 5),
    ("Normalization in DBMS", "Remember", 2),
    ("Dijkstra Algorithm", "Apply", 5),
    ("Neural Networks", "Understand", 3)
]



for topic, bloom, marks in test_inputs:
    print(f"\n🔹 {topic} | {bloom} | {marks} marks\n")

    q = generate_question(topic, bloom, marks)

    if q:
        print(json.dumps(q, indent=2))