# -*- coding: utf-8 -*-
"""Extract_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKcPUZ-pfeJdiu_IBH2nUdhFOllZtAsS
"""

from openai import OpenAI
from google.colab import userdata
userdata.get('GEMINI_API_KEY')
openai_api_key = userdata.get('OPENAI_API_KEY')
client = OpenAI(api_key=openai_api_key)

file = client.files.create(
    file=open("/content/AAI syllabus.pdf", "rb"),
    purpose="user_data"
)

resp = client.responses.create(
    model="gpt-4o-mini",
    input=[
        {
            "role": "user",
            "content": [
                {
                    "type": "input_file",
                    "file_id": file.id
                },
                {
                    "type": "input_text",
                    "text": "Extract all text exactly as shown. Preserve line breaks. Return only the text."
                }
            ]
        }
    ]
)

print(resp.output_text)

print(resp)

!pip -q install -U google-genai

from google import genai
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")
client = genai.Client(api_key=api_key)

pdf_path = "/content/AAI syllabus.pdf"

uploaded_file = client.files.upload(file=pdf_path)

prompt = """
Extract all text from this PDF exactly as shown.
Preserve line breaks, table structure and reading order.
Return only the extracted text, no summary, no commentary.
"""

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=[
        prompt,
        uploaded_file,
    ],
)

print(response.text)